### ISSUE TITLE
Changing number of cores produces errors

### ISSUE THREAD

**Issue by nrferguson** [CMAP-REPOS/cmap_csvm#33]
While testing release 0.3 on CMAP modeling servers, we found that with USER_PROCESSOR_CORES set to '1L' there are no issues. However, if the variable is changed, the error messages below are produced.

'8L'
<img width="674" alt="Capture8" src="https://user-images.githubusercontent.com/5191449/193725219-fd11d3da-6ae6-4dca-9375-0d25cb2844e6.PNG">

'4L'
<img width="674" alt="Capture4" src="https://user-images.githubusercontent.com/5191449/193725529-9f7fc316-93b7-4018-8119-af1eedb289fa.PNG">

'2L'
![Capture2](https://user-images.githubusercontent.com/5191449/193725330-4f19dcea-72af-4302-8147-d90f102a3e4e.PNG)

**Comment by ColSmith76** [comment]
@nrferguson thanks for the error report, we'll look at this as we update the CV model components

**Comment by ColSmith76** [comment]
Error due to temporarily for testing returning a list of all intermediate tables from CV model as well as the final output table, not handled correctly by parallel when it added together the outputs from the parallel process (can only reassemble a single table that has been split into chunks). Updated to final version with just the final output table and error is resolved.
